language: node_js
node_js:
  - "4.1"
  - "4.0"
services:
  - mongodb
env:
  - NODE_ENV === 'production'
before_install:
  - npm install -g grunt-cli
  - sudo apt-get install mongodb-org-server
before_script:
  - sleep 15

